FROM php:8.2-apache

# Habilita mod_rewrite
RUN a2enmod rewrite

# Copia solo la carpeta src al directorio público
COPY ./src/ /var/www/html/

# Establece permisos
RUN chown -R www-data:www-data /var/www/html
RUN chmod -R 755 /var/www/html

# Reinicia Apache para aplicar cambios
RUN service apache2 restart

# Expone el puerto 80
EXPOSE 80